### ISSUE TITLE
Can't instantiate org.arquillian.cube.docker.junit5.ContainerDsl

### ISSUE THREAD

**Issue by nicolasduminil** [arquillian/arquillian-cube#1316]
##### Issue Overview
Using `arquillian-bom:1.9.1.Final`, `arquillian-cub-*:1.18.2` and `arquillian-junit5-container:1.8.1:Final` to test a couple of REST services deployed in a Wildfly 33.0 bootable, ran as a Docker image, created by the `wildfly-maven-plugin`. I'm using the DSL based approach and try to instantiate the container object as follows:

      @ExtendWith(ContainerDslResolver.class)
      ...
      private static ContainerDsl wildfly = new ContainerDsl("...").withPortBinding(...)...;
      ...

##### Expected Behaviour

I expect that the code above works as explained in the documentation.

##### Current Behavior

The code above raises the following exception:

    java.lang.NoSuchMethodError: 'void  com.github.dockerjava.api.command.DockerCmdExecFactory.init(com.github.dockerjava.core.DockerClientConfig)'
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:161)
        at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
        at org.arquillian.cube.docker.impl.util.DefaultDocker.getDefaultDockerClient(DefaultDocker.java:13)
        at org.arquillian.cube.docker.impl.client.CubeDockerConfigurationResolver.resolveSystemDefaultSetup(CubeDockerConfigurationResolver.java:217)

After digging a bit, I came to the conclusion that `arquillian-cube-docker:1.18.2` includes `docker-java:3.0.14` which is in conflict with `docker-java:3.4.0` already in my project. I've tried to exclude `docker-java:3.0.14` from `arquillian-cube-docker:1.18.2` at build time and to force `docker-java:3.4.0` to be used instead, but of course, other exceptions are then raised, especially because the `javax.*` namespace, probably referenced by `arquillian-cube-docker:1.18.2`, isn't found any more.

I strongly suspect that the Arquillian artifacts versions I'm using aren't the most recent ones but I wasn't able to find anything more recent. How could I solve this conflict ?

##### Steps To Reproduce
I can provide a simple reproducer if required

##### Additional Information

```
<details>
  Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
  Maven home: /opt/apache-maven-3.9.5
  Java version: 21.0.3, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-21-oracle-x64
  Default locale: en_US, platform encoding: UTF-8
  OS name: "linux", version: "6.8.0-45-generic", arch: "amd64", family: "unix"
</details>
```

**Comment by nicolasduminil** [comment]
I can see that my last issue, registered in 2019, hasn't yet been assigned 4 years later. So I reckon that this project isn't active any more. Closing the issue, not because it is fixed but because it isn't worth continuing to post here.
