### ISSUE TITLE
PoolingHttpClientConnectionManager ClassNotFoundException

### ISSUE THREAD

**Issue by lucasweb78** [arquillian/arquillian-cube#172]
I gett the following exception:

```
Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.conn.PoolingHttpClientConnectionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:83)
	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:65)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:66)
	at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.<init>(DockerClientExecutor.java:137)
	at org.arquillian.cube.docker.impl.client.DockerClientCreator.createClient(DockerClientCreator.java:16)
```

when using Arquillian Cube. I am able to work around the issue be explicitly adding

```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.3</version>
            <scope>test</scope>
        </dependency>
```

to my pom.xml

If I only have the following dependencies in my pom.xml I see the exception:

Dependency Management
```
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>1.1.8.Final</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
```
Dependencies
```
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

       <dependency>
            <groupId>org.jboss.arquillian.junit</groupId>
            <artifactId>arquillian-junit-container</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-depchain</artifactId>
            <type>pom</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-arquillian-container-remote</artifactId>
            <version>8.2.0.Final</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.arquillian.cube</groupId>
            <artifactId>arquillian-cube-docker</artifactId>
            <version>1.0.0.Alpha7</version>
            <scope>test</scope>
        </dependency>
```

**Comment by lordofthejars** [comment]
So strange since we are using Cube and I have never found this exception.
It might be useful a dependency:tree output to see what s happening since
the missing dependency comes from a 3rd party and not Cube itself
El dt., 18 d’ag., 2015 a les 18.16 Rich Lucas <notifications@github.com> va
escriure:

**Comment by lucasweb78** [comment]
I've figured out this issue and it's specific to my dependencies.

I have a dependency which pulls in an older version of httpclient (4.2.6) which does not contain the PoolingHttpClientConnectionManager as this was introduced in 4.3.

Including httpclient 4.3 as a direct dependency in my pom solves this. I'm going to close this issue as it is not an Arquillian Cube problem.

**Comment by lordofthejars** [comment]
Nice thank you very much, it was strange but well you know sometimes strange things happens :)
