### ISSUE TITLE
Show a warning/exception if non localhost serverUri is defined and no certPath

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-cube#223]
If you do "docker-machine ls" and use serverUri=https://what.ever.the.machine.ip:port is, you get the following exception:

```java
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:490)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:143)
	at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.createContainer(DockerClientExecutor.java:337)
	at org.arquillian.cube.docker.impl.model.DockerCube.create(DockerCube.java:75)
	... 83 more
Caused by: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:99)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:443)
	... 99 more
```

The exception is due to a missing certificate to handle the SSL. Defining the correct "certPath" fixes this issue, but the exception message is a bit confusing. 

Not sure if we should throw exception on null certPath and 'remote ip' used, or go a bit safer route by catching the UnsupportedSchemeException and wrapping it in a new 'YouProbablyNeedToConfigureTheCertPathException'. I guess it is possible to add the remote certs in the default docker cert path or to the jvm etc..

**Comment by lordofthejars** [comment]
The problem is this exception is thrown by Docker-Java library. So maybe the best way to proceed would be catching the exception and rethrowing as IllegalStateException with the infor about hey you want to use https but probably there is not cert path or certificates are invalid.
