### ISSUE TITLE
Test fails if trying to stop container that's already been stopped

### ISSUE THREAD

**Issue by mikesir87** [arquillian/arquillian-cube#316]
**Background** - I'm working on building a setup in which I spin up a container for the app (wildfly-docker) and another container for Selenium (for Graphene/Drone testing).  To make things easier hostname-wise, the Selenium container is linked to the Wildfly container.  To make sure everything is ready for testing, I have an autoStartContainers set to start the Selenium container.  Since the Selenium container is linked to the wildfly-docker container, both are started up.

**Problem** - The test runs, everything is happy.  But, when trying to tear things down (I also have the clean option set), things blow up.  What I'm thinking is happening is that the test tears down the container being used for testing (wildfly-docker), but the autoStart (or clean?) is also trying to tear it down.  

Here's the exception...

```
Caused by: java.lang.RuntimeException: Could not auto stop container wildfly-docker
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.waitForCompletion(CubeSuiteLifecycleController.java:85)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.stopAllSteps(CubeSuiteLifecycleController.java:73)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.stopAutoContainers(CubeSuiteLifecycleController.java:45)
        ...
Caused by: org.arquillian.cube.spi.CubeControlException: Could not stop wildfly-docker
	at org.arquillian.cube.spi.CubeControlException.failedStop(CubeControlException.java:27)
	at org.arquillian.cube.docker.impl.model.DockerCube.stop(DockerCube.java:115)
	at org.arquillian.cube.impl.client.CubeLifecycleController.stop(CubeLifecycleController.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
        ...
Caused by: com.github.dockerjava.api.NotFoundException: no such id: wildfly-docker
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
```

**Fix** - I've prepared a PR (coming in just a moment) that modifies the ```DockerCube```'s ```stop``` and ```destroy``` methods to ignore ```NotFoundException```s.  If such an exception is thrown, the container has stopped and is no longer accessible, so has effectively been destroyed.  Therefore, it's not really an error and the rest of the teardown process can continue.

If you have another suggestion/idea on how to fix this, I'd love to chat and work on another idea!

**Comment by lordofthejars** [comment]
Could you paste the arquillian.xml file?

**Comment by mikesir87** [comment]
Here you go!

```xml
<arquillian xmlns="http://jboss.org/schema/arquillian"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="
    http://jboss.org/schema/arquillian
    http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

  <extension qualifier="docker">
    <property name="serverVersion">1.12</property>
    <property name="machineName">default</property>
    <property name="clean">true</property>
    <property name="autoStartContainers">regexp:(.*)</property>
    <property name="dockerContainers">
      wildfly-docker:
        buildImage:
          dockerfileLocation: src/test/resources/docker
          remove: true
        portBindings: [8080/tcp, 9990/tcp]
      selenium:
        image: selenium/standalone-chrome
        links:
          - wildfly-docker:wildfly
        portBindings: [4444/tcp]
        await:
          strategy: sleeping
          sleepTime: 3s
    </property>
  </extension>

  <container qualifier="wildfly-docker" default="true">
    <configuration>
      <property name="username">admin</property>
      <property name="password">admin</property>
      <property name="managementPort">9990</property>
    </configuration>
  </container>

</arquillian>
```

**Comment by mikesir87** [comment]
And I tried swapping the ```autoStartContainers``` property from the "select all" to just selenium.  Of course, starting just selenium still started the wildfly-docker container since it depends on it.  So, there was no change there.

**Comment by lordofthejars** [comment]
Ok I  now understand the problem correctly :) You PR fixes it and it is a good way to do it :) thank you very much for your help, and sorry for any inconvenience.

Alex.

**Comment by mikesir87** [comment]
No problem at all! You all did a great job writing it, so it was pretty easy to figure out what was going on and where to plug in a fix.  Thanks!
