### ISSUE TITLE
Fix transitive deps with jaxrs issues

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#57]
Fix transitive deps with jaxrs issues. Several users has found some issues when they were using RestEasy and docker cube, this is because docker-java uses Jersey as jaxrs provider and adds it as dependency on classpath so depending on the order of execution the test may fail.

It seems that docker-spotify project addresses this problem. For this reason we are going to move that library and see if the problem is fixed.

**Comment by rmpestano** [comment]
Hi @lordofthejars, to reproduce the issue just add dependency below to [ftests project](https://github.com/arquillian/arquillian-cube/tree/master/ftest):

```
<dependency>
          <groupId>org.jboss.resteasy</groupId>
          <artifactId>resteasy-jaxrs</artifactId>
          <version>2.3.3.Final</version>
         <scope>provided</scope>
 </dependency>
```
you should see the this error during test initialization:

```
Exception in thread "main" java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.resolveTemplate(Ljava/lang/String;Ljava/lang/Object;Z)Ljavax/ws/rs/core/UriBuilder;
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:246)
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:237)
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:59)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:23)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:47)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:26)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:282)
	at org.arquillian.cube.impl.docker.DockerClientExecutor.startContainer(DockerClientExecutor.java:290)
	at org.arquillian.cube.impl.model.DockerCube.start(DockerCube.java:80)
	at org.arquillian.cube.impl.client.CubeLifecycleController.start(CubeLifecycleController.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.arquillian.cube.impl.client.CubeSuiteLifecycleController.startAutoContainers(CubeSuiteLifecycleController.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:68)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:104)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160) 
```

**Comment by lordofthejars** [comment]
Perfect thank you so much, have you fixed? One guy has found similar problem and he has fixed by adding docker-java explicitly as first dependency.

**Comment by aslakknutsen** [comment]
Rely on https://github.com/aslakknutsen/docker-java/tree/pure_httpc

Discussion https://github.com/docker-java/docker-java/issues/133

**Comment by aslakknutsen** [comment]
I came across this as a possible workaround that works in the case where you don't really use RestEasy but 'some' JBoss EE lib is on classpath that provide the service registration for RestEasy..

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <systemPropertyVariables>
                        <!--  Force Jersey to be used when RestEasy is auto-discovered. Jersey is required by docker-java -->
                        <javax.ws.rs.ext.RuntimeDelegate>org.glassfish.jersey.internal.RuntimeDelegateImpl</javax.ws.rs.ext.RuntimeDelegate>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by lordofthejars** [comment]
Could we add this information to documentation?

**Comment by spec0p** [comment]
Has any decision been made on how to solve this? Are we dependent on some kind of action from the docker-java project, or is something that i could try to create pull request for?

**Comment by lordofthejars** [comment]
It is something related to docker-java, we provided a PR to them that didn't use any jaxrs implementation, just plain java, but they discarded

**Comment by spec0p** [comment]
I have been using the workaround on this thread for some time and it actually worked until i had to place a dependency on resteasy-client.  I wouldn't mind to put some effort on at least trying solve this. What are the alternatives?

**Comment by lordofthejars** [comment]
don't know, I would say wait until Java 9 modules comes. It is  a classloader problem because of transitive dependency of docker-java cc/ @bartoszmajsak

**Comment by spec0p** [comment]
Good point about the Java 9 modules.

**Comment by nickarls** [comment]
I'm also seeing this issue (discussion in https://developer.jboss.org/message/985015). In summary, I've tried
adding a test-scoped resteasy-client to the pom and using the system property that @aslakknutsen  proposed above but still no go. There is a pull request https://github.com/jboss/jboss-jaxrs-api_spec/pull/7 against the spec but a workaround would be nice.

**Comment by esteveavi** [comment]
Hi,
Still seeing this issue.
Any update @aslakknutsen 
Thank you very much.

**Comment by faiza-aslam** [comment]
I am also facing this same issue. Any updates on how to fix this, please?
