### ISSUE TITLE
Star operator not working with docker-compose file

### ISSUE THREAD

**Issue by acidowl** [arquillian/arquillian-cube#620]
Hi, 

as the title says: the star operator is not working with a docker-compose file.
My docker-compose.yaml:

```kolibridb:
  image: kolibri/db:latest
  expose:
    - "3306"
  volumes:
    - "./src/test/resources/initdb:/docker-entrypoint-initdb.d"
kolibrisrv*:
  image: kolibri/appserver:latest
  ports:
    - "8080:8080"
    - "9990:9990"
  expose:
    - "9990"
  links:
    - kolibridb:db
  volumes:
    - "./src/test/resources/config:/config"
    - "~/.m2/repository:/root/.m2/repository"
  privileged: true
```

Console output: 
```Running de.wspsoft.kolibri.selenium.tests.portal.DashboardTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in de.wspsoft.kolibri.selenium.tests.portal.DashboardTest
de.wspsoft.kolibri.selenium.tests.portal.DashboardTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.RuntimeException: Arquillian has previously been attempted initialized, but failed. See cause for previous exception
Caused by: java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
```

My dependencies:

```
<details>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>de.wspsoft.kolibri.platform</groupId>
    <artifactId>platform-parent</artifactId>
    <version>1.5.1</version>
  </parent>

  <artifactId>kolibri-integration-test</artifactId>
  <name>Kolibri :: Integration Test</name>
  <description>Runs integration test cases.</description>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.18.1</version>

        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <arquillian.launch>wildfly-managed</arquillian.launch>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <jboss.home>${project.basedir}/target/wildfly</jboss.home>
              </systemPropertyVariables>
              <redirectTestOutputToFile>false</redirectTestOutputToFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <properties>
    <jboss.home>${project.basedir}/target/wildfly</jboss.home>
    <version.selenium>3.2.0</version.selenium>
    <version.kolibri-feature-pack>1.5.1</version.kolibri-feature-pack>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.arquillian.cube</groupId>
        <artifactId>arquillian-cube-bom</artifactId>
        <version>1.0.0.Alpha19</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>2.8.7</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- Testing dependencies -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <!-- downgraded to version 4.11 because of http://stackoverflow.com/questions/25219233/arquillian-unsupportedoperationexception-when-use-insequence-annotation
        <version>4.11</version> -->
    </dependency>
    <dependency>
      <groupId>org.arquillian.cube</groupId>
      <artifactId>arquillian-cube-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-transaction-jta</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-transaction-jta</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-drone-webdriver-depchain</artifactId>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-remote-driver</artifactId>
      <version>${version.selenium}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-api</artifactId>
      <version>${version.selenium}</version>
    </dependency>

    <!-- Kolibri dependencies -->
    <dependency>
      <groupId>de.wspsoft.kolibri.platform</groupId>
      <artifactId>kolibri-designer</artifactId>
      <type>war</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>de.wspsoft.kolibri.platform</groupId>
      <artifactId>kolibri-script</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>de.wspsoft.kolibri.platform</groupId>
      <artifactId>platform-utils</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>de.wspsoft.kolibri.platform</groupId>
      <artifactId>application-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>de.wspsoft.kolibri.platform.wildfly-provisioning</groupId>
      <artifactId>kolibri-feature-pack</artifactId>
      <version>${version.kolibri-feature-pack}</version>
      <type>zip</type>
      <scope>test</scope>
    </dependency>

    <!-- Other dependencies -->
    <dependency>
      <groupId>org.hibernate.javax.persistence</groupId>
      <artifactId>hibernate-jpa-2.1-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>4.3.0.Final</version>
    </dependency>
    <dependency>
      <groupId>org.jboss.spec.javax.transaction</groupId>
      <artifactId>jboss-transaction-api_1.2_spec</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.enterprise</groupId>
      <artifactId>cdi-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>xml-apis</groupId>
      <artifactId>xml-apis</artifactId>
      <version>1.4.01</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>java-hamcrest</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>wildfly-cube</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.arquillian.cube</groupId>
          <artifactId>arquillian-cube-docker</artifactId>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.wildfly.arquillian</groupId>
          <artifactId>wildfly-arquillian-container-remote</artifactId>
          <version>2.0.2.Final</version>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>

</details>
```

docker --version: ```1.12.6 build 78d1802```
Java -version: ```java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)```
uname -a: ```Linux lt-fkaiser 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by lordofthejars** [comment]
Thank you very much for using Arquillian Cube and sorry for this inconvenience. Tomorrow morning I will take a look and provide a fix and release a new version with the fix.

**Comment by lordofthejars** [comment]
Hi I have written an `ftest` using star operator and docker compose and in my case it works.

So next questions are: have you tried the same without star operator? Just to discard where it is the problem if in the star operator or in another place. And also can you provide a full stack trace of the failure so we can detect where is the problem?

Thank you very much.

**Comment by acidowl** [comment]
Hi, without the star operator it is working fine in sequential order.

Here's the full stacktrace:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
DEBUG logging - Logging Provider: org.jboss.logging.Log4jLoggerProvider
Running de.wspsoft.kolibri.selenium.tests.designer.DesignerTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE! - in de.wspsoft.kolibri.selenium.tests.designer.DesignerTest
de.wspsoft.kolibri.selenium.tests.designer.DesignerTest  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:166)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:103)
	at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:52)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:114)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:162)
	... 20 more
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.arquillian.cube.docker.impl.client.config.DockerCompositions.overrideCubeProperties(DockerCompositions.java:135)
	at org.arquillian.cube.docker.impl.client.CubeDockerConfiguration.fromMap(CubeDockerConfiguration.java:269)
	at org.arquillian.cube.docker.impl.client.CubeDockerConfigurator.configure(CubeDockerConfigurator.java:88)
	at org.arquillian.cube.docker.impl.client.CubeDockerConfigurator.configure(CubeDockerConfigurator.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.bindAndFire(ManagerImpl.java:265)
	at org.jboss.arquillian.core.impl.InstanceImpl.set(InstanceImpl.java:74)
	at org.arquillian.cube.impl.client.CubeConfigurator.configure(CubeConfigurator.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.bindAndFire(ManagerImpl.java:265)
	at org.jboss.arquillian.core.impl.InstanceImpl.set(InstanceImpl.java:74)
	at org.jboss.arquillian.config.impl.extension.ConfigurationRegistrar.loadConfiguration(ConfigurationRegistrar.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.start(ManagerImpl.java:290)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.<init>(EventTestRunnerAdaptor.java:63)
	... 25 more


Results :

Tests in error: 
  DesignerTest.de.wspsoft.kolibri.selenium.tests.designer.DesignerTest » Runtime

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.311 s
[INFO] Finished at: 2017-03-08T11:11:42+01:00
[INFO] Final Memory: 55M/518M
[INFO] ------------------------------------------------------------------------
``` 

Thank you for your help!

**Comment by lordofthejars** [comment]
Finally can you also paste the arquillian.xml?

**Comment by acidowl** [comment]
Sure, forgot to add it:
```
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

  <container qualifier="kolibrisrv" default="true" mode="class">
    <configuration>
      <property name="managementAddress">127.0.0.1</property>
      <property name="managementPort">9990</property>
      <property name="username">kolibri</property>
      <property name="password">kolibri</property>
    </configuration>
  </container>

  <extension qualifier="docker">
    <property name="serverVersion">1.12.6</property>
    <property name="serverUri">http://127.0.0.1:2375</property>
    <property name="definitionFormat">COMPOSE</property>
    <property name="dockerContainersFile">docker-compose.yml</property>
    <property name="connectionMode">STARTANDSTOP</property>
    <property name="clean">true</property>
    <property name="cubeSpecificProperties">
      kolibrisrv:
        await:
          strategy: http
          responseCode: 200
          url: http://localhost:8080/idp
          sleepPollingTime: 10 s
          iterations: 15
    </property>
  </extension>

  <extension qualifier="webdriver">
    <property name="browser">chrome</property>
  </extension>
</arquillian>
```

**Comment by lordofthejars** [comment]
I have found the problem, you've found an error when putting custom properties in containers managed by star operator. :) Thank you very much.

**Comment by lordofthejars** [comment]
Ok I have found that there is no bug, you need to change 

```xml
<property name="cubeSpecificProperties">
      kolibrisrv:
        await:
          strategy: http
          responseCode: 200
          url: http://localhost:8080/idp
          sleepPollingTime: 10 s
          iterations: 15
    </property>
```

to

```xml
<property name="cubeSpecificProperties">
      kolibrisrv*:
        await:
          strategy: http
          responseCode: 200
          url: http://localhost:8080/idp
          sleepPollingTime: 10 s
          iterations: 15
    </property>
```
Notice that you need to add star operator as well.

I have updated the example as well.
