### ISSUE TITLE
Create a nowait strategy

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#63]
Create a nowait strategy which simply do nothing. SImply pass the check.

**Comment by rmpestano** [comment]
this will let us to start a docker container without connecting to it? eg: in my system  test (which runs in a "normal" arquillian container without docker)  i want to consume a rest endpoint  which is provided by a docker container but when I start this container i receive the error:

```
[31m22:00:47,542 ERROR [stderr] (default task-39) java.lang.RuntimeException: No command response within timeout of 30000 ms.
[0m[31m22:00:47,543 ERROR [stderr] (default task-39) 	at org.jboss.arquillian.protocol.servlet.runner.ServletCommandService.execute(ServletCommandService.java:60)
[0m[31m22:00:47,544 ERROR [stderr] (default task-39) 	at org.arquillian.cube.impl.client.container.remote.ContainerCubeController.start(ContainerCubeController.java:46)
[0m[31m22:00:47,544 ERROR [stderr] (default task-39) 	at com.cdi.crud.person.test.PersonIt.tearUp(PersonIt.java:43)
[0m[31m22:00:47,545 ERROR [stderr] (default task-39) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[0m[31m22:00:47,545 ERROR [stderr] (default task-39) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[0m[31m22:00:47,545 ERROR [stderr] (default task-39) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[0m[31m22:00:47,545 ERROR [stderr] (default task-39) 	at java.lang.reflect.Method.invoke(Method.java:483)
[0m[31m22:00:47,545 ERROR [stderr] (default task-39) 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
[0m[31m22:00:47,583 ERROR [stderr] (default task-39) 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[0m[31m22:00:47,584 ERROR [stderr] (default task-39) 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
[0m[31m22:00:47,584 ERROR [stderr] (default task-39) 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[0m[31m22:00:47,584 ERROR [stderr] (default task-39) 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
My test is passing cause i'm catching the exception, see [this image](http://i.imgur.com/2l0DTJ4.png).

car_service is the container which has the endpoint i want to consume on my test.

If it is true i think this is really the common case. Instead of connecting to a docker container I would like to create an usual arquillian test for the system itself and docker containers for other (external) resources the system depends on like other applications (the REST endpoint) or infrastructure like a mail service for example. This makes sense for you?   .

Also for my test example instead of @Before/@After I was thinking of an annotation like @UsingContainers() on the test method.

**Comment by lordofthejars** [comment]
Not exactly, in your case I think you need to use the shouldAllowToConnectToRunningContainers. NoWait strategy is used when Arquillian Cube starts a container and don't want to wait to know if the container is already up or not, simply wants to skip this step.

**Comment by aslakknutsen** [comment]
@rmpestano the Wait strategy is just a way to know when the Container has started. If you configure Cube to wait for the port that your car_service(rest endpoint) is running on, it 'should work' ?

**Comment by rmpestano** [comment]
@lordofthejars the container is not running but now i understand this issue.

@aslakknutsen  autoStartContainers was my first attempt but i got this error:

```
org.arquillian.cube.spi.CubeControlException: Could not start car_service
	at org.arquillian.cube.spi.CubeControlException.failedStart(CubeControlException.java:23)
	at org.arquillian.cube.impl.model.DockerCube.start(DockerCube.java:88)
	at org.arquillian.cube.impl.client.CubeLifecycleController.start(CubeLifecycleController.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.arquillian.cube.impl.client.CubeSuiteLifecycleController.startAutoContainers(CubeSuiteLifecycleController.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:68)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:104)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
Caused by: java.lang.IllegalArgumentException: Cannot connect to car_service container
	at org.arquillian.cube.impl.model.DockerCube.start(DockerCube.java:83)
	... 34 more
``` 

It fails in this check on DockerCube#start():

```
 if(!AwaitStrategyFactory.create(executor, this, configuration).await()) {
                throw new IllegalArgumentException(String.format("Cannot connect to %s container", id));
            }
```

thank you guys

**Comment by lordofthejars** [comment]
Ok if it is not started then maybe it is true that you need the nowait strategy as well.

**Comment by aslakknutsen** [comment]
@rmpestano If this is all localhost(meaning you're not running into any of the other open issues), then it sounds like "strategy: polling" combined with autoStartContainers should work (assuming you've configured the car_service image to expose ports etc )

**Comment by lordofthejars** [comment]
> @rmpestano If this is all localhost(meaning you're not running into any of the other open issues), then it sounds like "strategy: polling" combined with autoStartContainers should work (assuming you've configured the car_service image to expose ports etc )

Yes it should work. I think there is an example in ftest project. https://github.com/arquillian/arquillian-cube/blob/master/ftest/src/test/resources/arquillian.xml#L44

**Comment by rmpestano** [comment]
I have posted more information in arquillian space at  jboss forums to not pollute this issue:

https://developer.jboss.org/message/916560

**Comment by lordofthejars** [comment]
To not overpopulate the project with await strategies, you can use nowait but setting sleepingawait strategy to 0. Because there is a easy way to do this I close this issue
