### ISSUE TITLE
ClassNotFoundException: org.arquillian.cube.spi.CubeControlException

### ISSUE THREAD

**Issue by jamesnetherton** [arquillian/arquillian-cube#673]
##### Issue Overview

If you use CubeController in-container:

```java
@ArquillianResource
private CubeController cubeController;
```

And an exception is thrown someone within any of the cubeController method calls, it's tricky to find out exactly what went wrong, because you end up with:

```
Caused by: java.lang.ClassNotFoundException: org.arquillian.cube.spi.CubeControlException from [Module "deployment.arquillian-service:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.jboss.arquillian.protocol.jmx.Serializer.toObject(Serializer.java:48)
	... 33 more
```

**Comment by bartoszmajsak** [comment]
Just curious - why would you deploy cube to wildfly? What's your usecase?

**Comment by jamesnetherton** [comment]
See [here](https://github.com/wildfly-extras/wildfly-camel/tree/master/itests/standalone/docker/src/main/java/org/wildfly/camel/test). Basically to test stuff that relies on some external resources being available.

**Comment by lordofthejars** [comment]
Just to start discarding things, have you tried to run https://github.com/arquillian/arquillian-cube/blob/master/docker/ftest/src/test/java/org/arquillian/cube/servlet/CubeControllerTest.java

**Comment by dipak-pawar** [comment]
@jamesnetherton Could you please share your tests for which you are getting this exception. In above [link](https://github.com/wildfly-extras/wildfly-camel/tree/master/itests/standalone/docker/src/main/java/org/wildfly/camel/test) you have shared all the tests. 

We have ftests which are using

**Comment by jamesnetherton** [comment]
@dipak-pawar I just hacked together a basic demo here:

https://github.com/jamesnetherton/arquillian-cube-demo

I've deliberately misconfigured the 'await' params in `arquillian.xml` so that the `CubeController` will throw a `CubeControlException`. Note the resulting `ClassNotFoundException`.

**Comment by dipak-pawar** [comment]
thanks @jamesnetherton. I will take a look into it tomorrow.

**Comment by RajAsapu** [comment]
I imported '
```
<dependency>
    <groupId>org.arquillian.cube</groupId>
    <artifactId>arquillian-cube-spi</artifactId>
    <version>1.5.0</version>
</dependency>
```
which solved the issue for me.This repo has the CubeControlException class.

**Comment by lordofthejars** [comment]
But this dep should be automatically imported, hummm can you share you pom
with arquilian deps?

El dt., 13 de juny 2017 a les 15:50, R@j $ekh@r (<notifications@github.com>)
va escriure:

**Comment by jamesnetherton** [comment]
This issue is about `CubeControlException` not being available when the test runs in-container, so the Maven dependencies aren't really so relevant.

I tried adding the `arquillian-cube-spi ` dependency to my [sample project](https://github.com/jamesnetherton/arquillian-cube-demo) and as expected it makes no difference.

**Comment by lordofthejars** [comment]
Are you using ShrinkWrap right? Then try to add there by using Maven resolver.

**Comment by jamesnetherton** [comment]
Or we just add `CubeControlException` to the archive generated by `CubeAuxiliaryArchiveAppender`. It works, I just tested it.

If you're happy with that solution I'll submit a PR.

**Comment by lordofthejars** [comment]
Sure, PR are more than welcome. Thank you so much.
