### ISSUE TITLE
java.lang.UnsupportedClassVersionError: org/arquillian/cube/impl/client/container/remote/CubeRemoteExtension

### ISSUE THREAD

**Issue by mtau11** [arquillian/arquillian-cube#674]
I'm trying the Basic Example in the documentation. The example is set up to run again tutum/tomcat:7.0 which is bundled with jdk7. Is there a distribution containing this class that is compatible with jdk7? 

My test fails with:

Caused by: java.lang.UnsupportedClassVersionError: org/arquillian/cube/impl/client/container/remote/CubeRemoteExtension : Unsupported major.minor version 52.0 (unable to load class org.arquillian.cube.impl.client.container.remote.CubeRemoteExtension)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2961)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1210)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1690)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at org.jboss.arquillian.container.test.impl.RemoteExtensionLoader.load(RemoteExtensionLoader.java:236)
	at org.jboss.arquillian.container.test.impl.RemoteExtensionLoader.all(RemoteExtensionLoader.java:99)
	at org.jboss.arquillian.container.test.impl.RemoteExtensionLoader.load(RemoteExtensionLoader.java:70)
	at org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader.load(LoadableExtensionLoader.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.fireProcessing(ManagerImpl.java:346)
	at org.jboss.arquillian.core.impl.ManagerImpl.<init>(ManagerImpl.java:100)
	... 44 more

**Comment by dipak-pawar** [comment]
arquillian-cube is already running using `jre8`. Can  you try to tomcat image bundled with `jre8`? 

Look for example tests in [docker/ftest](https://github.com/arquillian/arquillian-cube/tree/master/docker/ftest
), [Dockerfile](https://github.com/arquillian/arquillian-cube/blob/master/docker/ftest/src/test/resources/tomcat/Dockerfile) for tomcat
