### ISSUE TITLE
Could not override docker registry thru arquillian.xml

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#738]
I am using arquillian to pull the images from my private repository but its always referring to registry-1.docker.io even though i tried to override it using the dockerRegistry flag.

**docker-compose.yml**
```
  ui:
    image: "test-epe-c-service:DEV"
    ports: ["4200:80"]
```

**arquillian.xml**

```
 <extension qualifier="docker">
        <property name="connectionMode">STARTANDSTOP</property>
        <!--<property name="serverVersion">17.05.0-ce</property>-->
        <!--<property name="serverUri">unix://var/run/docker.sock</property>-->
        <property name="dockerRegistry">https://docker-dev-local.jfrog.aws.company.com</property>
        <!--<property name="tlsVerify">true</property>-->
        <!--<property name="certPath">/etc/docker/certs.d</property>-->
        <property name="clean">true</property>
        <property name="dockerContainersFile">src/test/resources/docker-compose.yml</property>
        <property name="definitionFormat">COMPOSE</property>
        <property name="cleanBuildImage">true</property>
        <property name="autoStartContainers">ui</property>
    </extension>
```

**Docker daemon log:**
```
DEBU[0256] form data: {"ExposedPorts":{"80/tcp":{}},"HostConfig":{"PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"4200"}]},"ReadonlyRootfs":false},"Image":"test-epe-c-service:DEV","Volumes":{},"name":"ui"} 
ERRO[0256] Handler for POST /containers/create returned error: No such image: test-epe-c-service:DEV 
DEBU[0257] Calling POST /images/create?fromImage=test-epe-c-service&tag=DEV 
DEBU[0257] Trying to pull test-epe-c-service from https://registry-1.docker.io v2 
ERRO[0257] Not continuing with pull after error: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
 
INFO[0257] Ignoring extra error returned from registry: unauthorized: authentication required 
INFO[0257] Translating "denied: requested access to the resource is denied" to "repository test-epe-c-service not found: does not exist or no pull access" 
ERRO[0257] Handler for POST /images/create returned error: repository test-epe-c-service not found: does not exist or no pull access 
```

**Stack Trace:**

`CubeDockerConfiguration: 
  serverUri = unix:///var/run/docker.sock
  dockerRegistry = https://docker-dev-local.jfrog.aws.company.com
  tlsVerify = false
  dockerServerIp = localhost
  definitionFormat = CUBE
  autoStartContainers = ui
  clean = true
  removeVolumes = true
  dockerContainers = containers:
  ui:
    alwaysPull: false
    image: test-epe-c-service:DEV
    killContainer: false
    manual: false
    portBindings: [4200->80/tcp]
    readonlyRootfs: false
    removeVolumes: true
networks: {}

14:43:24,766 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:43:24,767 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:43:24,767 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/rasapu/Desktop/pricing-e2e-tests/build/resources/test/logback.xml]
14:43:24,946 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:43:24,963 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:43:24,986 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:43:25,044 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [pricing-e2e-tests] to DEBUG
14:43:25,044 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
14:43:25,044 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:43:25,045 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:43:25,046 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1df8da7a - Registering current configuration as safe fallback point
14:43:25.607 DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.command.CreateContainerCmdImpl@7895d668[name=ui,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env=<null>,cmd=<null>,entrypoint=<null>,image=test-epe-c-service:DEV,volumes=com.github.dockerjava.api.model.Volumes@62972f61,workingDir=<null>,macAddress=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@2fc07f86,stopSignal=<null>,hostConfig=com.github.dockerjava.api.model.HostConfig@31307af0[binds=<null>,blkioWeight=<null>,blkioWeightDevice=<null>,blkioDeviceReadBps=<null>,blkioDeviceReadIOps=<null>,blkioDeviceWriteBps=<null>,blkioDeviceWriteIOps=<null>,memorySwappiness=<null>,capAdd=<null>,capDrop=<null>,containerIDFile=<null>,cpuPeriod=<null>,cpuShares=<null>,cpuQuota=<null>,cpusetCpus=<null>,cpusetMems=<null>,devices=<null>,dns=<null>,dnsSearch=<null>,extraHosts=<null>,links=<null>,logConfig=<null>,lxcConf=<null>,memory=<null>,memorySwap=<null>,memoryReservation=<null>,kernelMemory=<null>,networkMode=<null>,oomKillDisable=<null>,oomScoreAdj=<null>,portBindings={80/tcp=[Lcom.github.dockerjava.api.model.Ports$Binding;@640803ac},privileged=<null>,publishAllPorts=<null>,readonlyRootfs=false,restartPolicy=<null>,ulimits=<null>,volumesFrom=<null>,pidMode=<null>,securityOpts=<null>,cgroupParent=<null>,volumeDriver=<null>,shmSize=<null>],labels=<null>,networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,execution=com.github.dockerjava.jaxrs.CreateContainerCmdExec@689004e7]
14:43:26.427 DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
14:43:26.438 DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
14:43:26.440 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection request: [route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
14:43:26.561 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection leased: [id: 0][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
14:43:26.563 DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->unix://localhost:80
14:43:26.591 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:80
14:43:26.592 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 
14:43:26.592 DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST /containers/create?name=ui HTTP/1.1
14:43:26.592 DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
14:43:26.595 DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
14:43:26.598 DEBUG org.apache.http.headers - http-outgoing-0 >> POST /containers/create?name=ui HTTP/1.1
14:43:26.599 DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: application/json
14:43:26.599 DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/json
14:43:26.600 DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5.3)
14:43:26.600 DEBUG org.apache.http.headers - http-outgoing-0 >> Transfer-Encoding: chunked
14:43:26.600 DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:80
14:43:26.600 DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
14:43:26.600 DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
14:43:27.033 DEBUG c.g.d.j.JerseyDockerCmdExecFactory - 1 * Sending client request on thread pool-1-thread-1
1 > POST unix://localhost:80/containers/create?name=ui
1 > Accept: application/json
1 > Content-Type: application/json
{"name":"ui","Image":"test-epe-c-service:DEV","Volumes":{},"ExposedPorts":{"80/tcp":{}},"HostConfig":{"PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"4200"}]},"ReadonlyRootfs":false}}

14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /containers/create?name=ui HTTP/1.1[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/json[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/json[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5.3)[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Transfer-Encoding: chunked[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:80[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "ba[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "{"name":"ui","Image":"test-epe-c-service:DEV","Volumes":{},"ExposedPorts":{"80/tcp":{}},"HostConfig":{"PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"4200"}]},"ReadonlyRootfs":false}}[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "0[\r][\n]"
14:43:27.034 DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
14:43:27.036 DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
14:43:27.036 DEBUG org.apache.http.wire - http-outgoing-0 << "Api-Version: 1.27[\r][\n]"
14:43:27.036 DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
14:43:27.036 DEBUG org.apache.http.wire - http-outgoing-0 << "Docker-Experimental: false[\r][\n]"
14:43:27.036 DEBUG org.apache.http.wire - http-outgoing-0 << "Server: Docker/17.03.1-ce (linux)[\r][\n]"
14:43:27.037 DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Fri, 16 Jun 2017 18:43:27 GMT[\r][\n]"
14:43:27.037 DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 52[\r][\n]"
14:43:27.037 DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
14:43:27.037 DEBUG org.apache.http.wire - http-outgoing-0 << "{"message":"No such image: test-epe-c-service:DEV"}[\n]"
14:43:27.041 DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 404 Not Found
14:43:27.042 DEBUG org.apache.http.headers - http-outgoing-0 << Api-Version: 1.27
14:43:27.042 DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/json
14:43:27.042 DEBUG org.apache.http.headers - http-outgoing-0 << Docker-Experimental: false
14:43:27.042 DEBUG org.apache.http.headers - http-outgoing-0 << Server: Docker/17.03.1-ce (linux)
14:43:27.042 DEBUG org.apache.http.headers - http-outgoing-0 << Date: Fri, 16 Jun 2017 18:43:27 GMT
14:43:27.043 DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 52
14:43:27.049 DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
14:43:27.060 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
14:43:27.060 DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
14:43:27.060 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 0][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
Jun 16, 2017 2:43:27 PM org.arquillian.cube.docker.impl.docker.DockerClientExecutor createContainer
WARNING: Docker Image test-epe-c-service:DEV is not on DockerHost and it is going to be automatically pulled.
14:43:27.092 DEBUG c.g.d.j.JerseyDockerCmdExecFactory - 2 * Sending client request on thread dockerjava-jaxrs-async-0
2 > POST unix://localhost:80/images/create?fromImage=test-epe-c-service&tag=DEV
2 > Accept: application/octet-stream
2 > Content-Type: application/json

14:43:27.092 DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
14:43:27.092 DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
14:43:27.092 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection request: [route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
14:43:27.093 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection leased: [id: 1][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
14:43:27.093 DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->unix://localhost:80
14:43:27.095 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:80
14:43:27.102 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 
14:43:27.102 DEBUG o.a.h.impl.execchain.MainClientExec - Executing request POST /images/create?fromImage=test-epe-c-service&tag=DEV HTTP/1.1
14:43:27.102 DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
14:43:27.102 DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> POST /images/create?fromImage=test-epe-c-service&tag=DEV HTTP/1.1
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> Accept: application/octet-stream
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Type: application/json
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5.3)
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> Host: localhost:80
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> Connection: Keep-Alive
14:43:27.102 DEBUG org.apache.http.headers - http-outgoing-1 >> Accept-Encoding: gzip,deflate
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "POST /images/create?fromImage=test-epe-c-service&tag=DEV HTTP/1.1[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept: application/octet-stream[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5.3)[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: localhost:80[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
14:43:27.102 DEBUG org.apache.http.wire - http-outgoing-1 >> "[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 404 Not Found[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Api-Version: 1.27[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Type: application/json[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Docker-Experimental: false[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Server: Docker/17.03.1-ce (linux)[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Fri, 16 Jun 2017 18:43:27 GMT[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Length: 88[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
14:43:27.898 DEBUG org.apache.http.wire - http-outgoing-1 << "{"message":"repository test-epe-c-service not found: does not exist or no pull access"}[\n]"
14:43:27.898 DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.1 404 Not Found
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Api-Version: 1.27
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Content-Type: application/json
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Docker-Experimental: false
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Server: Docker/17.03.1-ce (linux)
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Date: Fri, 16 Jun 2017 18:43:27 GMT
14:43:27.899 DEBUG org.apache.http.headers - http-outgoing-1 << Content-Length: 88
14:43:27.899 DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
14:43:27.899 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-1: Close connection
14:43:27.899 DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
14:43:27.900 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 1][route: {}->unix://localhost:80][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
14:43:27.907 ERROR c.g.d.c.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.NotFoundException: {"message":"repository test-epe-c-service not found: does not exist or no pull access"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

java.lang.RuntimeException: Could not auto start container ui

	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.waitForCompletion(CubeSuiteLifecycleController.java:107)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.startAllSteps(CubeSuiteLifecycleController.java:80)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController.startAutoContainers(CubeSuiteLifecycleController.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:92)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:116)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.arquillian.cube.spi.CubeControlException: Could not create ui
	at org.arquillian.cube.spi.CubeControlException.failedCreate(CubeControlException.java:15)
	at org.arquillian.cube.docker.impl.model.DockerCube.create(DockerCube.java:117)
	at org.arquillian.cube.impl.client.CubeLifecycleController.create(CubeLifecycleController.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController$StartCubes.call(CubeSuiteLifecycleController.java:146)
	at org.arquillian.cube.docker.impl.client.CubeSuiteLifecycleController$StartCubes.call(CubeSuiteLifecycleController.java:130)
	at org.jboss.arquillian.core.impl.threading.ThreadedExecutorService$ContextualCallable.call(ThreadedExecutorService.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"repository test-epe-c-service not found: does not exist or no pull access"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	... 4 more`

**Comment by lordofthejars** [comment]
https://github.com/arquillian/arquillian-cube/issues/632

If IIRC you also need to set username and password

**Comment by RajAsapu** [comment]
@lordofthejars : tried with that as well but no luck.

**Comment by lordofthejars** [comment]
can you paste the new arquillian.xml, I have several working examples that runs on private Docker repositories, so it seems there is something wrong on configuration.

**Comment by RajAsapu** [comment]
@lordofthejars : Please take a look at the above description , it has the arquillian file and the docker log as well. Let me know if you need any further information.

**Comment by lordofthejars** [comment]
I think that Docker mandates that image name should contain the docker registry url in case of not using the docker hub.

**Comment by RajAsapu** [comment]
@lordofthejars May be , are you using docker registry url in your docker compose file for your working examples !

**Comment by lordofthejars** [comment]
IIRC yes. Another thing we can do is just prepare an example that works
with bintray so you can share the project and we can debug exactly what is
the missing pieces. See the example here how the image contains the host
https://blog.docker.com/2013/07/how-to-use-your-own-registry/

El dl., 26 de juny 2017 a les 16:05, R@j $ekh@r (<notifications@github.com>)
va escriure:

**Comment by RajAsapu** [comment]
@lordofthejars : Could you please try with registry in docker compose and remove the docker registry override in the arquillian.xml and check if its still pulling images from the private registry!

**Comment by RajAsapu** [comment]
@lordofthejars When ever you have some time please try the above case . I believe overriding of the registry from arquillian cube is not working lets see.

**Comment by AndyGee** [comment]
If `<property name="dockerRegistry">my.reg.com</property>` is specified, then it should be prefixed to internal names like these:

`
    private static final String VNC_IMAGE = "richnorth/vnc-recorder:latest";
    private static final String CONVERSION_IMAGE = "arquillian/flv2mp4:0.0.1";
`
