### ISSUE TITLE
Allow to connect to running container is not working 

### ISSUE THREAD

**Issue by mgreau** [arquillian/arquillian-cube#77]
Hi,

I've a Docker container currently running, it was started by a docker command and when I want to execuate my tests with this container, I've the error below. I added the property shouldAllowToConnectToRunningContainers.

Maybe I forget to add some configuration ?
You can find all my informations below : 

## Stacktrace :
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.584 sec <<< FAILURE! - in org.asciidoctor.ConverterServletTest
org.asciidoctor.ConverterServletTest  Time elapsed: 5.583 sec  <<< ERROR!
java.lang.IllegalStateException: Can't get binding for cube wildfly82 when status not STARTED or PRE_RUNNING. Status is DESTROYED
	at org.arquillian.cube.impl.model.DockerCube.bindings(DockerCube.java:130)
	at org.arquillian.cube.impl.client.container.ProtocolMetadataUpdater.update(ProtocolMetadataUpdater.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)

```

## PC configuration:
```
* OS : 
	Ubuntu 14.04 LTS
* Cube
    version 1.0.0.Alpha3
*Docker : 
	Client version: 1.4.1
	Client API version: 1.16
	Go version (client): go1.3.3
	Git commit (client): 5bc2ff8
	OS/Arch (client): linux/amd64
	Server version: 1.4.1
	Server API version: 1.16
	Go version (server): go1.3.3
	Git commit (server): 5bc2ff8
```

## How to reproduce

```
1. git clone https://github.com/mgreau/asciidoctor-wildfly-docker.git
2. cd asciidoctor-wildfly-docker
3. docker build -t asciidoctor/wildfly82 src/test/resources/wildfly/v8.2/
4. sudo docker run -p 9991:9990 --name="wildfly82" -d asciidoctor/wildfly82 
5. mvn clean test -Pwildfly82
```

## JSON Object 
http://127.0.0.1:2375/v1.16/containers/wildfly82/json
```
{"AppArmorProfile":"","Args":["-b","0.0.0.0","-bmanagement","0.0.0.0"],"Config":{"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["/opt/jboss/wildfly/bin/standalone.sh","-b","0.0.0.0","-bmanagement","0.0.0.0"],"CpuShares":0,"Cpuset":"","Domainname":"","Entrypoint":null,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","JAVA_HOME=/usr/lib/jvm/java","WILDFLY_VERSION=8.2.0.Final","JBOSS_HOME=/opt/jboss/wildfly","ASCIIDOCTORJ_VERSION=1.5.2","JRUBY_VERSION=1.7.16.1","ASCIIDOCTORJ_PDF_VERSION=1.5.0-alpha.6","ASCIIDOCTORJ_EPUB3_VERSION=1.5.0-alpha.4","ASCIIDOCTORJ_MODULE=/opt/jboss/wildfly/modules/org/asciidoctor/main","URL_BASE=https://repo1.maven.org/maven2/"],"ExposedPorts":{"8080/tcp":{},"9990/tcp":{}},"Hostname":"18b09c0dcdc9","Image":"asciidoctor/wildfly82","MacAddress":"","Memory":0,"MemorySwap":0,"NetworkDisabled":false,"OnBuild":null,"OpenStdin":false,"PortSpecs":null,"StdinOnce":false,"Tty":false,"User":"jboss","Volumes":null,"WorkingDir":"/opt/jboss"},"Created":"2015-01-27T00:21:32.069724562Z","Driver":"aufs","ExecDriver":"native-0.2","HostConfig":{"Binds":null,"CapAdd":null,"CapDrop":null,"ContainerIDFile":"","Devices":[],"Dns":null,"DnsSearch":null,"ExtraHosts":null,"IpcMode":"","Links":null,"LxcConf":[],"NetworkMode":"bridge","PortBindings":{"9990/tcp":[{"HostIp":"","HostPort":"9991"}]},"Privileged":false,"PublishAllPorts":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":""},"SecurityOpt":null,"VolumesFrom":null},"HostnamePath":"/var/lib/docker/containers/18b09c0dcdc92d1f284536736a89239d23f4b5fe2342351e36948ed14dfbbcf4/hostname","HostsPath":"/var/lib/docker/containers/18b09c0dcdc92d1f284536736a89239d23f4b5fe2342351e36948ed14dfbbcf4/hosts","Id":"18b09c0dcdc92d1f284536736a89239d23f4b5fe2342351e36948ed14dfbbcf4","Image":"320857a0746741e23783860018ceabf7f44f5136a60406694ed89bf2bc40d1c3","MountLabel":"","Name":"/wildfly82","NetworkSettings":{"Bridge":"docker0","Gateway":"172.17.42.1","IPAddress":"172.17.0.20","IPPrefixLen":16,"MacAddress":"02:42:ac:11:00:14","PortMapping":null,"Ports":{"8080/tcp":null,"9990/tcp":[{"HostIp":"0.0.0.0","HostPort":"9991"}]}},"Path":"/opt/jboss/wildfly/bin/standalone.sh","ProcessLabel":"","ResolvConfPath":"/var/lib/docker/containers/18b09c0dcdc92d1f284536736a89239d23f4b5fe2342351e36948ed14dfbbcf4/resolv.conf","State":{"Error":"","ExitCode":0,"FinishedAt":"0001-01-01T00:00:00Z","OOMKilled":false,"Paused":false,"Pid":7686,"Restarting":false,"Running":true,"StartedAt":"2015-01-27T00:21:32.239476702Z"},"Volumes":{},"VolumesRW":{}}
```

**Comment by lordofthejars** [comment]
Are you running tests incontainer or as client?

**Comment by mgreau** [comment]
As client with this configuration : 

```java
@Deployment(testable = false)
	public static WebArchive create() {
```

**Comment by lordofthejars** [comment]
strange because I have tested as client and a tomcat and it worked. Probably I will need to download the code and debug to see what's happen. But I think the problem is here https://github.com/arquillian/arquillian-cube/blob/master/docker/src/main/java/org/arquillian/cube/impl/client/container/CubeContainerLifecycleController.java#L47 that we should change the status of the cube to STARTED because in fact it is started.

**Comment by lordofthejars** [comment]
Yes this is the problem, this afternoon I will fix it.

**Comment by mgreau** [comment]
Cool ! you're the best :)

**Comment by lordofthejars** [comment]
Fixed, this afternoon I will push the code.
