### ISSUE TITLE
NPE when deploy a WAR with @Deployment method

### ISSUE THREAD

**Issue by acidowl** [arquillian/arquillian-cube#812]
When deploying a war with @Deployment method I always get a NPE.
Stacktrace:
<details>
```
java.lang.NullPointerException
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.validate(DeploymentGenerator.java:99)
	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:87)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:201)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:426)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:218)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:166)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

This is my deployment method:
```
  @Deployment(testable = false, name = "idpDeployment", order = 1)
  @TargetsContainer("test_kolibrisrv*")
  public static WebArchive createIdpDeployment() {
    System.out.println("Deploying idp...");
    String baseDir = System.getProperty("basedir");

    File warFile = new File(baseDir.substring(0, baseDir.lastIndexOf('/'))
        + "/kolibri-wildfly/identity-provider/target/identity-provider.war");

    WebArchive webArchive = ShrinkWrap.createFromZipFile(WebArchive.class, warFile);
    webArchive.delete("WEB-INF/classes/META-INF/BaseApplication-persistence.xml");
    webArchive.addAsResource("persistence/idp-persistence.xml", "META-INF/persistence.xml");

     return webArchive;    
  }
```

And these are my docker containers defined in arquillian.xml:
```
      test_kolibridb*:
        image: kolibri/db:latest
        exposedPorts: [3306/tcp]
        privileged: true
        portBindings: [3306/tcp]
        await:
          strategy: sleeping
          sleepTime: 30 s

      test_kolibrisrv*:
        image: kolibri/testserver:latest
        exposedPorts: [8080/tcp, 9990/tcp]
        links:
          - test_kolibridb*:db
        privileged: true
        portBindings: [8080/tcp, 9990/tcp]
        await:
          strategy: sleeping
          sleepTime: 30 s
```

We're currently using arquillian-cube-bom @ version 1.9.0
Also these dependencies were used:
```
                <dependency>
                    <groupId>org.arquillian.cube</groupId>
                    <artifactId>arquillian-cube-docker</artifactId>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>org.jboss.arquillian.core</groupId>
                    <artifactId>arquillian-core-impl-base</artifactId>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>org.jboss.arquillian.test</groupId>
                    <artifactId>arquillian-test-impl-base</artifactId>
                    <scope>test</scope>
                </dependency>
                <dependency>
                    <groupId>org.wildfly.arquillian</groupId>
                    <artifactId>wildfly-arquillian-container-managed</artifactId>
                    <version>2.1.0.Final</version>
                    <scope>test</scope>
                </dependency>
```

Maven version: 3.5.0
OS: Ubuntu 16.04
JDK Version: 1.8.0_144

Is there anything wrong with our deployment method or is this a bug?

**Comment by lordofthejars** [comment]
It does not seem a problem with cube since the exception occurs when arquillian is validating deployment file. Have you tried the same example but wihtout using Cube? Which App server are you using?

**Comment by acidowl** [comment]
No, I haven't. It's a wildfly server, forgot to mention earlier.

**Comment by lordofthejars** [comment]
Then try outside cube, just for example embedded wildfly using chameleon https://github.com/arquillian/arquillian-container-chameleon or scaffolding with Forge to check where is exactly the problem.

**Comment by mbrasier** [comment]
This occurs if there is no <container> configured in arquillian.xml (or at least that was the issue for me).

**Comment by mbrasier** [comment]
No `<container>` element
