### ISSUE TITLE
NPE on shutdown using arquillian cube

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#957]
##### Issue Overview

I get an NPE on shutdown, when arquillian cube is trying to kill a container. The NPE occurs while firing an event. It trying to get a scoped context, which is null, so triggers an NPE.

```
[WARNING] useSystemClassloader setting has no effect when not forking
Running org.apache.bookkeeper.tests.TestCompatUpgrade
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 116.721 sec - in org.apache.bookkeeper.tests.TestCompatUpgrade

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:15 min
[INFO] Finished at: 2018-01-18T12:35:47+01:00
[INFO] Final Memory: 362M/1541M
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-3" org.arquillian.cube.spi.CubeControlException: Could not stop bookkeeper3_f623d52e-92a0-442f-b926-f22f66f211bb
        at org.arquillian.cube.spi.CubeControlException.failedStop(CubeControlException.java:23)
        at org.arquillian.cube.docker.impl.model.DockerCube.stop(DockerCube.java:170)
        at org.arquillian.cube.impl.client.ForceStopDockerContainersShutdownHook$1.run(ForceStopDockerContainersShutdownHook.java:19)
Caused by: java.lang.NullPointerException
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:128)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
        at org.arquillian.cube.docker.impl.model.DockerCube.stop(DockerCube.java:152)
        ... 1 more
[INFO] Scanning for projects...
```

##### Expected Behaviour

No NPE, the docker container should be deleted.

##### Current Behaviour

NPE, docker container orphaned.

##### Steps To Reproduce
1. Pull https://github.com/ivankelly/bookkeeper/tree/bc-tests-wip
2. mvn install -Pdocker -DskipTests
3. cd tests/backward-compat-upgrade/
4. mvn test -DintegrationTests

##### Additional Information

```
~/src/bookkeeper $ mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_IE, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-5-amd64", arch: "amd64", family: "unix"
```

**Comment by bartoszmajsak** [comment]
https://github.com/arquillian/arquillian-core/issues/153
