### ISSUE TITLE
Kubernetes connection is not closed

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#976]
When you run a tests using OpenShift/Kubernetes you get next warning 

```
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. 
Did you forget to close a response body? To see where this was allocated, 
set the OkHttpClient logger level to 
FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```

check why this is happening and close the stream if it is necessary.

**Comment by lordofthejars** [comment]
After doing some exploratory testing I have seen that this does not occurs in our `ftests` but it happens to next project https://github.com/lordofthejars/wfswarm-rest-http when I run `mvn clean verify -Popenshift,openshift-it`. The big difference is that one is using FMP and the other not. So what I recommend is that try to run tests from Maven in project https://github.com/arquillian-testing-microservices/zero-config-deployment-test which also uses FMP and then try to run tests from Maven in https://github.com/arquillian-testing-microservices/openshift-deployment-testing project. If it only happens in FMP projects then the problem probably is that FMP does not close the resources and it is not a Cube error.

**Comment by hemanik** [comment]
On setting the level to FINE, the logs show this coming from [WatchConnectionManager.java#L145](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L145).
```
Feb 15, 2018 10:52:18 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://192.168.42.69:8443/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
    at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
    at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
    at okhttp3.RealCall.enqueue(RealCall.java:87)
    at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:180)
    at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:427)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:145)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:97)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:701)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:689)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.periodicWatchUntilReady(HasMetadataOperation.java:200)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.waitUntilReady(HasMetadataOperation.java:227)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:78)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:33)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1.run(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
Considering, this is used for the purpose of watching, forcefully closing the stream leads to environment not initialised problem. Not sure if this is as per design or there is something missing to be fixed.

Opened a related issue in the [fabric8io/kubernetes-client/issues/1013](https://github.com/fabric8io/kubernetes-client/issues/1013) to validate if this needs to be fixed on the f8 side or else on the Cube front.

**Comment by hemanik** [comment]
Will be fixed with https://github.com/fabric8io/kubernetes-client/pull/1042.
